{% set name = "RadGEEToolbox" %}
{% set version = "1.7.7" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/d4/98/04571d0b12718feba72da6ff9406fe7dc5737bc07d9d969834d62e09eb04/radgeetoolbox-1.7.7.tar.gz
  sha256: 1dc990647f344a91a4cc819178e67ed4ee5f283d4ad05146fd446885391e5589

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - earthengine-api
    - numpy
    - pandas
    - matplotlib
    - cartopy
    - Pillow
    - python >={{ python_min }}

test:
  imports:
    - RadGEEToolbox
  commands:
    - pip check
  requires:
    - python {{ python_min }} 
    - pip

about:
  home: https://github.com/radwinskis/RadGEEToolbox
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Streamlined Multispectral & SAR Analysis for Google Earth Engine Python API"
  doc_url: https://radgeetoolbox.readthedocs.io/en/latest/
  dev_url: https://github.com/radwinskis

extra:
  recipe-maintainers:
    - radwinskis
