{% set name = "RadGEEToolbox" %}
{% set version = "1.7.10" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/65/9f/0fe11fd6f77d7660ec840a5d215e828d44755ce8bcee5c2a37dfe77f15c3/radgeetoolbox-1.7.10.tar.gz
  sha256: bfcefde8b704d407273d1d7921ea51a0abf1c910dfa9fdbbb863dc36a12f9baa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - earthengine-api
    - numpy
    - pandas
    - matplotlib-base
    - cartopy
    - Pillow
    - python >={{ python_min }}

test:
  imports:
    - RadGEEToolbox
  commands:
    - pip check
  requires:
    - python {{ python_min }} 
    - pip

about:
  home: https://github.com/radwinskis/RadGEEToolbox
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Streamlined Multispectral & SAR Analysis for Google Earth Engine Python API"
  doc_url: https://radgeetoolbox.readthedocs.io/en/latest/
  dev_url: https://github.com/radwinskis

extra:
  recipe-maintainers:
    - radwinskis
