{% set name = "RadGEEToolbox" %}
{% set version = "1.7.8" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/c1/71/831af38e9912ec6a08205bcb8aa64d1d807699836620739ffbd622dad2b4/radgeetoolbox-1.7.8.tar.gz
  sha256: 1441303846e1a84a54039b040f0a66a291e0d464b0503c59a6a26c1a0fcf02ae

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - earthengine-api
    - numpy
    - pandas
    - matplotlib-base
    - cartopy
    - Pillow
    - python >={{ python_min }}

test:
  imports:
    - RadGEEToolbox
  commands:
    - pip check
  requires:
    - python {{ python_min }} 
    - pip

about:
  home: https://github.com/radwinskis/RadGEEToolbox
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Streamlined Multispectral & SAR Analysis for Google Earth Engine Python API"
  doc_url: https://radgeetoolbox.readthedocs.io/en/latest/
  dev_url: https://github.com/radwinskis

extra:
  recipe-maintainers:
    - radwinskis
